### ISSUE TITLE
Groups?

### ISSUE THREAD

**Issue by gr8bit** [iendeavor/vue-next-select#103]
Hi all,

one feature the vue-select-package was (and is!) missing is the possibility to have option groups (similar to the html select). Anyone thought about this yet?

Feature wishlist:
* "Group options" (=the option that is a group "headline") selectable or not selectable and with own option value
* Nested groups on 1+ levels
* Individual "group option" and options in group rendering (slots?) per level

Cheers! :)

**Comment by valh1996** [comment]
+1 I am really looking for that! I can't find any alternative components on Vue3...

**Comment by iendeavor** [comment]
@gr8bit @valh1996 Sorry for not getting back to you sooner.

In order to support as many as possible use cases (e.g, nested groups) and keep it flexible as well, it would be great if there have a prop `group-by` which is used to determine whether an option is group.

When click on a group option, all of its values (the value must be an Array) will be selected.

```js
const options = ref([
  { label: 'All', value: ['i', 'love', 'vue'], group: true }, // click on this option will select all options.
  { label: 'I', value: 'i' },
  { label: 'Love', value: 'love' },
  { label: 'Vue', value: 'vue' },
])
```

I have added some test cases for this blueprint too, please see [this test file](https://github.com/iendeavor/vue-next-select/commit/9b2e611f439be37513950fcd0353cd0ce0fdcb37).

Thank you for your time.

**Comment by gr8bit** [comment]
@iendeavor very cool! One thought though: what about disabling a group of elements...?

**Comment by iendeavor** [comment]
Maybe there should add `group-disabled-by` prop?

**Comment by gr8bit** [comment]
I think the normal disabled-by/disabled mechanism should suffice for the groups as well.

**Comment by iendeavor** [comment]
Yes, you are right 👍 , I will keep this in mind, but I need to go to sleep now 😄 .

**Comment by gr8bit** [comment]
Well deserved! 😄

**Comment by iendeavor** [comment]
It is released 😄 .
