### ISSUE TITLE
Performance issue when using lot of options

### ISSUE THREAD

**Issue by LeMinaw** [iendeavor/vue-next-select#212]
The performance of `vue-next-select` is relatively poor when reaching thousand of options.

## To reproduce

This can be experienced on this tweak of the `playground` demo with 6000 options:

https://codesandbox.io/s/vue-next-select-performance-n93oq

Just open/close the select and hover on dropdown items, latency should be quite obvious.

## Expected behavior

Better performance - possibly by allowing the user to disable some event listeners? From the profiler view, a lot of time is spent dealing with `mousemove` events when hovering options.

## Screenshots

Profiler view. Red time span is during select dropdown open, yellow ones are during options hover. See how rendering speed collapses from 60 to 1/2 FPS.

![image](https://user-images.githubusercontent.com/3968360/121221277-14836a00-c88e-11eb-9714-bf299c45ac8d.png)

## Desktop
 - OS: Win 10
 - Browser : Firefox
 - Version: 89

**Comment by mttzzz** [comment]
confirm this. we need a lite version :)

**Comment by iendeavor** [comment]
Thanks for your feedback ❤️ 

I made some changes to improve performance and will release it in the next version.

---

Also, if it is very large, no one wants/needs to browse all these options.

On the contrary, it may be better to use the **search/filter** feature in this case, so that we can also **limit the size** of the `options` through the `visible-options`:

```javascript
const option = ref(['foo', 'bar'])

const filterText = ref('foo')

const visibleOptions = computed(() => {
  return options.value
    .filter(option => option.startsWith(filterText.value))
    .slice(0, 999)) // <- limit to 999
})
```
