### ISSUE TITLE
Close when clicking on parent

### ISSUE THREAD

**Issue by timchesney** [iendeavor/vue-next-select#239]
Firstly - great component, thanks! 

**Idea/Issue**
It feels natural to be able to close the dropdown by clicking on the main element (e.g. the input) again. 
Currently, doing so causes a 'flash' where the dropdown closes on mouseDown but then opens again on mouseUp. 

Secondly, if you use the 'Toggle' slot for a custom toggle icon, clicking this no longer works to close the dropdown. 

**Solution**
Either make it the default behaviour or provide an option to make clicking anywhere on the main element close the dropdown. 

**GIF to show what I mean**

![CleanShot 2021-06-30 at 14 42 58](https://user-images.githubusercontent.com/30231/123894004-893f5500-d9b1-11eb-81b0-0eed7ef54a44.gif)

Thanks again.

**Comment by iendeavor** [comment]
Thank you for the feedback 😄 .

1. The 'flash' issue is fixed in 58ab2bf63bc9be0565d86635330fae571f361652, and released in v2.7.0, maybe you can try upgrade it.

2. I will research for this, but since changing this behavior will introduce a breaking change I will expose a new prop to achieve different behavior.

    > It feels natural to be able to close the dropdown by clicking on the main element (e.g. the input) again

3. Did you register the click event on custom toggle slot by the exposed [toggle function](https://iendeavor.github.io/vue-next-select/api-reference.html#toggle-2).

    I also noticed it [works properly on button](https://github.com/iendeavor/vue-next-select/blob/develop/cypress/integration/slots/toggle/index.html#L35) but span 😞 , I will fix it.

    > if you use the 'Toggle' slot for a custom toggle icon, clicking this no longer works to close the dropdown

**Comment by timchesney** [comment]
Thanks for the reply - much appreciated - hadn't used the toggle function so will give that a go... I should have read more carefully! All the best.

**Comment by iendeavor** [comment]
LMK if it doesn't works 🙇‍♂️ .

**Comment by iendeavor** [comment]
@timchesney I noticed you reopen this issue. Does this still not work 🤔 ?
