### ISSUE TITLE
Required field

### ISSUE THREAD

**Issue by ilyen85** [iendeavor/vue-next-select#256]
First of all, thank you for your work :)
**Describe the bug**
I'm not sure if this a bug or I'm just missing something. But is it possible that vue-next-select fields can't handle the required property? I haven't found it in the api reference, and setting a vue-next-select field to required will not trigger html5 validation.

**Expected behavior**
Trigger html5 validation

**Comment by iendeavor** [comment]
The required is not not yet implemented.

I will fix this weekend.

Ref: https://html.spec.whatwg.org/multipage/form-elements.html#attr-select-required

Thanks for the feedback 👍 .

**Comment by iendeavor** [comment]
@ilyen85 

Since vue-next-select is not implemented base on **native select**, there is a trade-off between supporting html validation and a lot of other features (e.g., styling select, Object options).

Instead of use native html required attribute I would first recommend you to use vuelidate to do validation, I have create an example for this: https://github.com/iendeavor/vue-next-select/blob/develop/examples/src/views/Vuelidate.vue .

Hope this helps you!

**Comment by ilyen85** [comment]
Hi!

Thank you for the example, yes I have managed to solve it with some JS validation, its just a nice to have feature ;) should I close this issue?

Thank you!
