### ISSUE TITLE
create button in case of no results for a search

### ISSUE THREAD

**Issue by akc4** [iendeavor/vue-next-select#278]
Would be helpful to have the ability to show a create button which can redirect to a creation page in case no results were found for a search.

Something like this:
<img width="435" alt="nores" src="https://user-images.githubusercontent.com/70768667/129046566-2a3cbee2-e09d-44aa-9848-a63b561f892a.png">

**Comment by iendeavor** [comment]
@akc4 

We could handle [search:input](https://iendeavor.github.io/vue-next-select/api-reference.html#search-input) event and pass [visible-option](https://iendeavor.github.io/vue-next-select/api-reference.html#visible-options) prop to achieve this feature:

[Demo](https://rvn9e.sse.codesandbox.io/vue-next-select/creatable)

[Code](https://codesandbox.io/s/github/iendeavor/vue-next-select/tree/develop/examples?from-embed=&file=/src/views/Creatable.vue)

**Comment by akc4** [comment]
@iendeavor 

Thank you for your reply.

That is not quite exactly what I was thinking, in that example it add's the typed search into the options array.

What I want is to show the `no results found` and a redirect link without having to add it to the options array in case there a no results for the search. But I haven't figured out how to keep the dropdown open, it closes if there are no results found in the options.

**Comment by iendeavor** [comment]
@akc4 😂

I create an example for this case:

https://codesandbox.io/s/vue-next-select-278-ch4gt?file=/src/views/Creatable.vue

In the example, we use the mentioned approach too:

We handle `search:input` event, pass `visible-option` prop and customize options by `dropdown-item` slot.

But rather than add a new **text** option, we could add a `Symbol` to distinguish and show special `no results found` option.

Hope this help!

**Comment by akc4** [comment]
Thank you I'll play with that.
